In [25]:
# Creating a dataset of images that can be used in model making.
#And for that I am using python library to scrape the images

**DATA GATHERING**

In [2]:
!pip install bing-image-downloader #installing this bing library to download images 

In [3]:
!mkdir images #making a directory named "images" to save all the images that we gonna download
#we can see a folder is created with the name "images" in the "Files" on the left hand side.

mkdir: cannot create directory ‘images’: File exists


In [4]:
from bing_image_downloader import downloader as ddr 
# bing_image_downloader is a python package to download images from bing. So we are using downloader library to download images from bing.
ddr.download("cricket ball", limit=40,output_dir='images') 
'''I am downloading 40 images of cricket ball using this function. And we are specifying the no. of images to be downloaded using "limit" parameter.
By default limit is 100 and I don't want those many images. So restricting it to 40.'''
'''We have also specified the directory in which these images need to be stored using "output_dir" parameter and given the value as 'images' so that images are saved in
 that directory which we have created earlier'''

[%] Downloading Images to /content/images/cricket ball


[!!]Indexing page: 1

[%] Indexed 40 Images on Page 1.


[%] Downloading Image #1 from https://5.imimg.com/data5/SELLER/Default/2020/8/AA/IL/QR/4931499/sf-true-test-red-leather-cricket-ball-500x500.png
[%] File Downloaded !

[%] Downloading Image #2 from https://n1.sdlcdn.com/imgs/a/x/p/SS-True-Test-Cricket-Ball-SDL133148022-1-b71cd.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://5.imimg.com/data5/SELLER/Default/2020/11/CS/KG/HN/60515312/ball-true-test-500x500.jpg
[Error]Invalid image, not saving https://5.imimg.com/data5/SELLER/Default/2020/11/CS/KG/HN/60515312/ball-true-test-500x500.jpg

[!] Issue getting: https://5.imimg.com/data5/SELLER/Default/2020/11/CS/KG/HN/60515312/ball-true-test-500x500.jpg
[!] Error:: Invalid image, not saving https://5.imimg.com/data5/SELLER/Default/2020/11/CS/KG/HN/60515312/ball-true-test-500x500.jpg

[%] Downloading Image #3 from https://www.sportcart.in/products/2020/376/truetestle

'We have also specified the directory in which these images need to be stored using "output_dir" parameter and given the value as \'images\' so that images are saved in\n that directory which we have created earlier'

In [5]:
# you can now check the output in the images directory. A sub folder is created in images directory under the name "cricket ball" and all the 40 images are saved in it

In [6]:
ddr.download("sunflower", limit=40,output_dir='images') 
# Now I am downloading another set of images of sunflower as I need atleast 2 classes of data to perform image classification
# The parameters are same as I expalined earlier and just the name of 'output_dir' changes as we need to save these images seperatly and we named it 'sunflower'

[%] Downloading Images to /content/images/sunflower


[!!]Indexing page: 1

[%] Indexed 40 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/originals/61/47/55/6147551345b8b4a353e61d018000d6ff.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://pics.me.me/shes-a-sunflower-strong-and-bold-and-true-to-herself-43765264.png
[%] File Downloaded !

[%] Downloading Image #3 from https://thegardeningcook.com/wp-content/uploads/2019/07/sunflower-true-friends-quote.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/b9/48/3e/b9483ef3471b287ccbdac25fc8adf256.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/474x/23/1f/c2/231fc2acae8dce76252eff28db0435b8.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.croatia-times.com/wp-content/uploads/2017/07/Sunflowers-of-Slavonia-Emica-Elvedji-HANZA-MEDIA-10.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/origina

In [7]:
# you can now check the output in the images directory. A sub folder is created in images directory under the name "sunflower" and all the 40 images are saved in it

**DATA PRE PROCESSING**

So, now as we have the images as our dataset, we need to process them in such a way that they are suitable to be fed into an ML model

In [8]:
#Importing all the required libraries
import os # I will use this operating system library to access the folders,
import numpy as np #I will use this library to perform some mathematical and numerical operations. 
from skimage.io import imread # I will use this scikit image, an image processing package to read an image using 'imread' library
from skimage.transform import resize # I will use this scikit image transform package to transform the image as required. 

In [10]:
#Creating empty lists to store the values of the data
target = [] #list to store the prediction 
images = [] #list to store the images
flattened_data=[] #list to stored the flattened images data, in such a way that it is suitable to the ML model. 

DATADIR = "/content/images" #creating a variable "DATADIR" to store the directory path which can used to access the data
CATEGORIES = ['cricket ball','sunflower'] #and these categories will be our targets while performing classification.
for i in CATEGORIES:
  class_num = CATEGORIES.index(i) #Label encoding the categories as it is in text format and we need to quantify them. 
  path = os.path.join(DATADIR,i) #used os library to join the paths of the CATEGORIES with the DATADIR to use all the images
  for img in os.listdir(path): #for loop to read all the images in each category with the help of 'path' created above.
    img_array = imread(os.path.join(path,img)) #reading one image after another in each category and storing it in the img_array
#each image data is stored in 3 dimensional array in the img_array and we need to flatten all of them.  
    img_resized = resize(img_array,(100,100,3)) #resizing all the images into a uniform scale of pixels(0 to 1) and storing it in the 'img_resized' array
    flattened_data.append(img_resized.flatten()) #flattening the resized images and apending them in the 'flattened_data' list that we created above
    images.append(img_resized) #storing the resized images in 'images' list that we created above
    target.append(class_num) 
flattened_data = np.array(flattened_data) #converting arrays into numpy arrays just in case if they are not converted into numpy arrays already
images = np.array(images)
target = np.array(target) #having in numpy is easy to work with and iterate through


Lets see what is stored in each of these variables

In [11]:
flattened_data #it is all pixel values of every image and it is flattened in 1 Dimension

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.84705882, 0.8745098 , 0.93333333, ..., 0.56078431, 0.48782353,
        0.12311765],
       [0.96470588, 0.96470588, 0.96470588, ..., 0.96470588, 0.96470588,
        0.95686275]])

In [12]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Now as the data is ready in required format. let us split the data into train data and test data 

In [13]:
from sklearn.model_selection import train_test_split #importing "train_test_split" library from "sklearn.model_selection" package
x_train,x_test,y_train,y_test = train_test_split(flattened_data,target,test_size=0.3,random_state=0) 
'''feeding 'flattened_data' as x, 'target' as  y into the "train_test_split" function to split train and test data where 30% of data goes 
into test data set and 70% into train data set'''
#small part of data is enough for test data set.
#we can give any random value into random_state parameter

'feeding \'flattened_data\' as x, \'target\' as  y into the "train_test_split" function to split train and test data where 30% of data goes \ninto test data set and 70% into train data set'

**MODEL MAKING**

SELECTING SVM (SUPPORT VECTOR MACHINE) ALGORITHM FOR THIS CLASSIFICATION PROBLEM

BEFORE ACTUALLY USING SVM, WE NEED TO FIND BEST & APPROPRIATE VALUES FOR PARAMETERS IN SVM LIKE 1. REGULARISATION PARAMETER(C) 2. KERNEL 3. GAMMA
THAT WILL BE SUITABLE FOR OUR DATA. 
AND FOR THAT LET'S USE GRID SEARCH CV

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [16]:
#trying out different values for parameters of svm so that the GridSearchCV can help us to pick the best ones. 
param_grid = [
         {'C':[1,10,50,100],'kernel':['linear']},
         {'C':[1,10,50,100],'gamma':[0.001,0.0001],'kernel':['linear']},
]
svc = svm.SVC(probability=True) 
'''setting the probability parameter as true for our svm model so that it will tell us the probability of its classification and
 from that we can also know the accuracy of the model'''
clf = GridSearchCV(svc,param_grid) #loading the model and parameters into the GridSearchCV so that it chooses the best variant of given 2 variants in param_grid 
clf.fit(x_train,y_train) #fitting the x_train & y_train into the model for training

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 50, 100], 'kernel': ['linear']},
                         {'C': [1, 10, 50, 100], 'gamma': [0.001, 0.0001],
                          'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [17]:
y_pred = clf.predict(x_test) #testing the model with x_test
y_pred #y_pred is the classification made by model on x_test

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1])

In [18]:
y_test #actual values for the x_test to the categories they belong to

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1])

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix
#importing accuracy_score and confusion_matrix to know the accuracy of the model 

In [20]:
accuracy_score(y_pred,y_test) #we got accuracy score as 83%. that means our model is 83/100 times makes proper classification

0.8333333333333334

In [24]:
confusion_matrix(y_pred,y_test) 
#this means our model predicted 20 items correctly into their respective categories and wrongly classified 4 items

array([[ 8,  3],
       [ 1, 12]])

THE ACCURACY OF THE MODEL CAN BE FURTHER IMPROVED BY CHOOSING MORE VALUES IN GRID SEARCH CV AND SELECTING BEST OUT OF MANY MORE POSSIBILITIES

**THE END**